language: c
sudo: required

os:
    - osx


compiler:
  #- gcc
  - gcc-7
  #- clang
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test # gcc
        packages:
            - gcc-7
            - make
            - cmake
            - cmake-data


before_install:
      - echo uname -a
      - echo gcc -v
      - brew update && brew upgrade
      - brew install cmocka



script:
  - make
  - ls -l
  - pwd
  # tests
  - make testall
  - make clean
  - make distclean