language: c
sudo: false # only for faster builds

before_install:
      - echo uname -a
      - echo gcc -v
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
        then brew upgrade ; brew install cmocka ;
        fi


script:
  - clang -coverage -O0 -lcmocka  helloCmocka.c -o hello
  - ./hello
  - gcov helloCmocka.c


after_success:
  - bash <(curl -s https://codecov.io/bash)
